# Generated by Django 4.1.1 on 2022-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_owner',
            name='r_password',
        ),
        migrations.AddField(
            model_name='pg_owner',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
