# Generated by Django 4.1.1 on 2022-09-24 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0010_pg_owner_any_view_pg_owner_bed_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/icon')),
            ],
        ),
        migrations.CreateModel(
            name='pg_amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.amenitie')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.pg_owner')),
            ],
        ),
    ]
